### PR TITLE
US116_Completed

### PR DESCRIPTION
**Pull request by Gulustann**
US116 test execution is completed. There is a bug relates to drivers access to checkbox on Vehicle Costs page. A bug report has been created and assigned to developer.

Thanks,
Gulustan

### CODE REVIEW

**Comment by SaianaD** [comment]
Everything looks good.

**Review by evgheniadarii — APPROVED** [review]
All looks good

**Review by Sndmp — APPROVED** [review]
Everything looks good.

**Comment by Kazim2022** [comment]
All good

**Pull request closed without merging**
